databases:
  - name: Select Drama_DB
    databaseName: select_drama_db
    user: Select Drama
    region: singapore

services:
  - type: web
    name: Select Drama
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Select Drama_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
